"""Wire-format constants from docs/PROTOCOL.md."""

# Opcodes (host -> device)
OP_PING = 0x01
OP_GET_ID = 0x02
OP_I2C_WRITE = 0x10
OP_I2C_READ = 0x11
OP_I2C_WRITE_READ = 0x12
OP_SPI_XFER = 0x20
OP_SET_CONFIG = 0x30
OP_GET_STATUS = 0x31
OP_SELF_TEST = 0x40

# Status codes (device -> host)
STATUS_ACK = 0x06
STATUS_NACK = 0x15
STATUS_ERR_CHECKSUM = 0x16
STATUS_ERR_LEN = 0x17
STATUS_ERR_OPCODE = 0x18

STATUS_NAMES = {
    STATUS_ACK: "ACK",
    STATUS_NACK: "NACK",
    STATUS_ERR_CHECKSUM: "ERR_CHECKSUM",
    STATUS_ERR_LEN: "ERR_LEN",
    STATUS_ERR_OPCODE: "ERR_OPCODE",
}

# SET_CONFIG (0x30) PARAM_IDs
PARAM_I2C_CLKDIV = 0x01
PARAM_SPI_CLKDIV = 0x02
PARAM_SPI_MODE = 0x03
PARAM_CS_POLARITY = 0x04

# cmd_engine's MAX_PAYLOAD parameter default (rtl/cmd_engine.v)
DEFAULT_MAX_PAYLOAD = 16

# GET_ID (0x02) response
DEVICE_VERSION = 0x01
DEVICE_ID = 0xA5

# SELF_TEST (0x40) response RDATA[0] flag bits, and the fixed byte it
# shifts out on SPI CS0 (see docs/PROTOCOL.md)
SELF_TEST_PATTERN = 0x5A
SELF_TEST_I2C_BUS_IDLE = 0x01
SELF_TEST_SPI_LOOPBACK = 0x02
